### ISSUE TITLE
image error in api

### ISSUE THREAD

**Issue by 823863429** [MoonRide303/Fooocus-MRE#107]
Using the api request, the final picture you get is like this.
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/6307936/dfc9d2e8-33dc-424c-bf86-83a0607dd181)

Several pictures are mixed in one picture, how should I deal with it? It's a bit urgent, please reply to me as soon as possible, thank you

**Comment by MoonRide303** [comment]
@823863429 It sometimes happens when you specify resolution that is far from 1:1 aspect ration and/or total pixels much higher than 1 MP (native SDXL resolution).

If you need higher resolution output you can try doing it in 2 passes:
1) use txt2img with resolution supported by SDXL (total pixel count close to 1 MP),
2) upscale output from 1) via Enhance Image or in Image-2-Image mode (you can look at the example in [wiki](https://github.com/MoonRide303/Fooocus-MRE/wiki/Upscaling-using-Image%E2%80%902%E2%80%90Image)).

I am closing this issue, as I cannot do much about it - it's just how diffusion models work.
