### ISSUE TITLE
Random seed with multiple images

### ISSUE THREAD

**Issue by ptits** [MoonRide303/Fooocus-MRE#137]
When rendering multiple images Random checkbox assign random seed only to first image, and seeds for other images are just increments +1.
Expected (imo) that it will be random seeds for all images in the batch

**Comment by MoonRide303** [comment]
@ptits Nope, it's not necessary for all seeds to be random:
1) changing seed by 1 can get you completely different results from the previous seed. It doesn't matter if it's +1 or +1000000,
2) only first seed being random is really important - because it will result in all the seeds being far away from range typically used by most people.
