### ISSUE TITLE
Feature Request: Abort button

### ISSUE THREAD

**Issue by theelefant** [MoonRide303/Fooocus-MRE#17]
In the original repository maintained by Illyasviel, I submitted a feature request for an 'Abort Button' for image generation
(see [Issue #85](https://github.com/lllyasviel/Fooocus/issues/85)).
However, it appears that this request has since been overshadowed by 100+ subsequent issues. Would it be possible for this repository to consider implementing this feature?

**Comment by barepixels** [comment]
Yeah this is pretty important.  Imagine setting a a batch of 32 and then realizing you chose the wrong Lora

**Comment by MoonRide303** [comment]
For most casual users doing batches of 1-4 images that's probably not that big deal, but I also understand people are sometimes doing larger batches and/or have slower computers, and then being able to cancel the task can be useful thing. I am not sure yet about what would be the best way to implement it (in terms of Gradio & Comfy internals), but I will try figuring it out.

**Comment by barepixels** [comment]
In Comfygui, Manager extension, there is a cancel button that will immediately stop the generating process.  From the CMD window, you can see "Processing interrupted".

What is cool is if you press the Queue button without making any changes since canceled, Comfygui will resume where it left off and not have to start from the beginning. 
![queue](https://github.com/MoonRide303/Fooocus-MRE/assets/92839033/d13fdef6-7445-4b6e-aeee-dd7c3918e96a)

**Comment by MoonRide303** [comment]
@theelefant @barepixels Done (commit [e0484f9](https://github.com/MoonRide303/Fooocus-MRE/commit/e0484f95293ec9a6bfbef49e426884b3bafdc4dc)).

**Comment by theelefant** [comment]
Great! Many thanks!
