### ISSUE TITLE
Prompt strengths adjustment function when text-to-image processing

### ISSUE THREAD

**Issue by shingo1228** [MoonRide303/Fooocus-MRE#93]
Regarding the text prompt strength adjustment feature, it currently seems to work for text-to-image processing(not image-2-image). Is this intentional?
I don't think this strength adjustment feature is necessary when text-to-image processing.

**Comment by MoonRide303** [comment]
@shingo1228 It is intentional, and it is necessary - cause it's useful for workflows like [Revision](https://github.com/MoonRide303/Fooocus-MRE/wiki/Revision), which can be used in both txt2img and img2img modes.

txt2img is when your initial latent is completely random.
img2img is when your initial latent is generated from existing image (with customizable amount of noise, depending on how much of this initial image you want to preserve).

So those modes, txt2img and img2img are just about your starting point, the initial latent.

Then comes the prompts (and/or revision), which apply conditioning to generation process. Prompt Strength is something similar to strength sliders for Revision images - it determins how strongly your text prompts will affect generation process. It can be lowered when you're using Revision, if you see text prompt is affecting generated image to much (you can even reduce it to 0, if you wish to do conditioning using only the images).

**Comment by shingo1228** [comment]
@MoonRide303 Thank you for your response. I understand the function of "Revision" during text-to-image processing and the role of "prompt strength".
